# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e705acc29a98d1b2880f41937c305db9ad20075dc5bdab1d7fbb6c4712f51dbb726968d64e6f3e72dbfc8715f704c08d5d82d5f6efb9b58b4d371f60cce9e3a

test:
  secret_key_base: b66ac3d1f588c598ec4b9aa3f9834b40a9cf768c34f9f92d2b843ce7e2bafcdff7f6f60ecb96277e58b21ba9602e3a397315b0de11a20ec0e254139d6c3daa3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
